name: SpawnerSilk
main: me.crylonz.spawnersilk.SpawnerSilk
version: "5.9.2"
author: Crylonz
softdepend: [ShopGUIPlus]
description: Mine and manage mob spawners with Silk Touch
api-version: "1.13"

commands:
  givespawner:
    description: Give a spawner to a target player
    usage: /givespawner <player> <spawnerType> [amount]
    permission: spawnersilk.givespawner
    aliases: [gs]
  editspawner:
    description: Edit the spawner block you are looking at
    usage: /editspawner <spawnRange|spawnCount|maxNearbyEntities|requiredPlayerRange|delay|maxSpawnDelay|minSpawnDelay> [value]
    permission: spawnersilk.editspawner
    aliases: [es]
  sps:
    description: Main command for SpawnerSilk
    usage: /sps <subcommand>
permissions:
  spawnersilk.minespawner:
    description: Allows players to mine spawners
    default: true
  spawnersilk.givespawner:
    description: Allows players to give spawners with a command
    default: op
  spawnersilk.editspawner:
    description: Allows players to edit spawners with a command
    default: op
  spawnersilk.overlay:
    description: Allows players to view spawner overlay information
    default: op
  spawnersilk.reload:
    description: Allows players to reload the plugin
    default: op
